README.md, docs/code-samples/factory.sol, docs/operating/accounts.md, docs/operating/transaction-gas.md
@YYYurchenko can we merge this with high priority please -- as I can only make code public for Shruti to refer to it from boilerplate Remix/hardhat whatever by getting this into production
=> Prod 158 factory contract

README.md, docs/developing/deploy_facilities/using_hardhat.md, docs/developing/deploy_facilities/using_truffle.md, docs/developing/integrate/wallets/integrating_walletconnect.md, docs/faq/neon-brief-faq.md, docs/governance/technical_implementation/vote.md, docs/operating/configuration.md, docs/wallet/metamask_setup.md
False positive: 
https://devnet.neonevm.org → Status: Error message provided to curl request
https://github.com/neonlabsorg/neonpass-ui/blob/5588478e7d421d07dd21b8440e6e0d6dd91d5fca/src/token-transfer/services/tokens-list.service.ts#L175-L184 → Status: User must be logged in
Uncertain:
https://testnet.neonevm.org → Status: times out
https://mainnet.neonevm.org → Status: no error message provided to curl request
Commented out:
https://www.notion.so/neonlabs/Neon-Specific-API-methods-3402baaad8fa4daeb12642495cf85eb3 → Status: this sits inside metadata // let's comment these out
=> fixes: links and ids false positives

docs/architecture/neon_evm_arch.md, docs/developing/connect_rpc.md, docs/operating/enhanced.md, docs/operating/transaction-gas.md, docs/tokens/token_list.md, docs/wallet/metamask_setup.md
and zero gas for operators (that was beta feature only)
=> Post beta: clearout beta and testnet mentions

README.md, docs/developing/get-started.md, docs/evm_compatibility/overview.md, docs/operating/operator-introduction.md, sidebars.js
I am so very confused -- I touched 3 files
I recognise the other edits BUT these are on a different branch on a different commit -- how did I break git?
=> Prod 170 get started

docs/developing/integrate/neon_transfer.mdx
This PR adds the repository link in the documentation.
=> Add the repository link to clone

docs/evm_compatibility/precompiles.md
This PR adds some missing words in one line.
=> Add some missing words

docs/faq/neon-brief-faq.md
This PR is for a single change for replacing Truffle with Foundry reference an a line.
=> Remove truffle and add foundry reference

docs/architecture/eth_sol_solution.md
This PR adds Hardhat and Foundry references replacing Truffle in the documentation.
=> Add Hardhat and Foundry references

docs/developing/get-started.md
This PR changes some links and removes outdated documentation (truffle documentation since it is no longer maintained).
=> Fixes in get started documentation

docs/developing/integrate/indexer/flair.md, sidebars.js
=> feat: add flair indexing

docs/developing/integrate/indexer/flair.md
@mnedelchev-vn this is FAO you to fix step 2 as per the hiccup you found, pls
=> to open PR FAO Miro

docs/about/neon_ecosystem.mdx, docs/about/why_neon.mdx
This PR adds Foundry tool to some specific instances and changes some lines for better readability. This PR will be in draft since the Foundry tutorial link has to be added first to the documentation.
=> Add Foundry in some places

docs/tokens/token_list.md
This PR adds the new tokens to the Mainnet list for NeonPass.
=> Add new tokens in the Mainnet list for NeonPass

docs/api/neon-api.mdx
Proxy API is WIP (managed by [This docs ticket](https://www.notion.so/neonfoundation/Document-the-API-f6b10616eb204949a564623440dbfc51?pvs=4))
=> DRAFT: Prod 160 proxy api

docs/api/neon-api.mdx, docs/developing/deploy_facilities/configure_foundry.md, docs/developing/deploy_facilities/using_hardhat.mdx, docs/governance/command_line.md, docs/governance/technical_implementation/vote.md
New QA linter for typos: responds to hits
=> fixes typos

docs/api/neon-api.mdx, static/schemas/neon-api/v1/neon_emulate/request.json, static/schemas/neon-api/v1/neon_emulate/response.json, static/schemas/neon-api/v1/neon_gasPrice/request.json, static/schemas/neon-api/v1/neon_getEvmParams/request.json, static/schemas/neon-api/v1/neon_getEvmParams/response.json, static/schemas/neon-api/v1/neon_getLogs/response.json, static/schemas/neon-api/v1/neon_getSolanaTransactionByNeonTransaction/request.json, static/schemas/neon-api/v1/neon_getSolanaTransactionByNeonTransaction/response.json, static/schemas/neon-api/v1/neon_getTransactionReceipt/request.json, static/schemas/neon-api/v1/neon_getTransactionReceipt/response.json, static/schemas/neon-api/v1/neon_versions/request.json
This branch updates the WIP API
=> Updates Prod 160 proxy api

docs/developing/deploy_facilities/using_foundry.md
This PR adds documentation about the scripts for deployment of contracts in the Foundry example.
=> Documentation about scripts for deployment in Foundry example

docs/developing/integrate/indexer/subsquid.md, sidebars.js
This PR adds a page for documenting the integration for Subsquid SDK.
=> Add Subsquid SDK integration example

docs/operating/basic.md
This PR adds an important note to mention that this set up of local proxy in this example works only with Neon EVM Devnet.
=> Add an important note to mention about Devnet

docs/composability/using_composability/swap_on_raydium.md, sidebars.js
This PR adds a page to demonstrate a swap on Raydium DEX via the composability feature on Solana.
=> Add Raydium Swap example

docs/composability/SDK - Solana Native.md, docs/evm_compatibility/overview.md, docs/tokens/gas_fees.mdx
Solana Signer SDK Documentation was added
=> SDK - Solana Native

docs/about/neon_ecosystem.mdx, sidebars.js
* NeonScan -> BlockScout in neon_ecosystem.mdx
- Removed menu "Tools" in sidebars.js
=> Tba 293 replace neonscan
